apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kitchen.fullname" . }}
  labels:
    {{- include "kitchen.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kitchen.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kitchen.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kitchen.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image }}"
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /etc/gcp/credentials.json
            - name: GCP_PROJECT_ID
              valueFrom:
                secretKeyRef:
                  name: gcp-credentials
                  key: project
            - name: SUBSCRIPTION
              value: "{{ .Values.subscription }}"
            - name: CHECK
              value: "{{ .Values.check }}"
            - name: GIN_MODE
              value: release
            - name: PORT
              value: "8000"
          volumeMounts:
          - mountPath: "/etc/gcp"
            name: gcp-credentials
            readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: gcp-credentials
          secret:
            secretName: gcp-credentials
            items:
            - key: credentials
              path: credentials.json
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
