replicaCount: 1

image: external-resources-aws-demo-kitchen:latest
queue: 
check:
credentials:
  secret:
    name: aws-credentials

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}


securityContext: {}

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: true
  className: ""
  annotations:
    dev.okteto.com/generate-host: "kitchen"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  
resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
