# file: .github/workflows/preview-closed.yaml
on:
  pull_request:
    types:
      - closed

jobs:
  closed:
    runs-on: ubuntu-latest
    steps:
    - name: Context
      uses: okteto/context@latest
      with:
        url: ${{secrets.OKTETO_URL}}
        token: ${{ secrets.OKTETO_TOKEN }}

    - name: Destroy preview environment
      uses: okteto/destroy-preview@latest
      with:
        name: oktaco-gcp-pr-${{ github.event.number }}
